/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard/route'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as AuthVerifyImport } from './routes/auth/verify'
import { Route as AuthSignupImport } from './routes/auth/signup'
import { Route as AuthResetImport } from './routes/auth/reset'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as AuthForgotImport } from './routes/auth/forgot'
import { Route as DashboardSetupRouteImport } from './routes/dashboard/setup/route'
import { Route as DashboardHomeRouteImport } from './routes/dashboard/home/route'
import { Route as DashboardFinancesRouteImport } from './routes/dashboard/finances/route'
import { Route as DashboardFinancesIndexImport } from './routes/dashboard/finances/index'
import { Route as DashboardSetupRulesImport } from './routes/dashboard/setup/rules'
import { Route as DashboardSetupMerchantsImport } from './routes/dashboard/setup/merchants'
import { Route as DashboardSetupCategoriesImport } from './routes/dashboard/setup/categories'
import { Route as DashboardSetupAccountsImport } from './routes/dashboard/setup/accounts'
import { Route as DashboardHomeStatsImport } from './routes/dashboard/home/stats'
import { Route as DashboardHomeOverviewImport } from './routes/dashboard/home/overview'
import { Route as DashboardHomeNetWorthImport } from './routes/dashboard/home/net-worth'
import { Route as DashboardFinancesTransactionsImport } from './routes/dashboard/finances/transactions'
import { Route as DashboardFinancesBudgetsImport } from './routes/dashboard/finances/budgets'
import { Route as DashboardBudgetsYearMonthDayImport } from './routes/dashboard/budgets/$year/$month/$day'

// Create/Update Routes

const DashboardRouteRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const AuthVerifyRoute = AuthVerifyImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRoute,
} as any)

const AuthResetRoute = AuthResetImport.update({
  id: '/auth/reset',
  path: '/auth/reset',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthForgotRoute = AuthForgotImport.update({
  id: '/auth/forgot',
  path: '/auth/forgot',
  getParentRoute: () => rootRoute,
} as any)

const DashboardSetupRouteRoute = DashboardSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardHomeRouteRoute = DashboardHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardFinancesRouteRoute = DashboardFinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => DashboardRouteRoute,
} as any)

const DashboardFinancesIndexRoute = DashboardFinancesIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardFinancesRouteRoute,
} as any)

const DashboardSetupRulesRoute = DashboardSetupRulesImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => DashboardSetupRouteRoute,
} as any)

const DashboardSetupMerchantsRoute = DashboardSetupMerchantsImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => DashboardSetupRouteRoute,
} as any)

const DashboardSetupCategoriesRoute = DashboardSetupCategoriesImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => DashboardSetupRouteRoute,
} as any)

const DashboardSetupAccountsRoute = DashboardSetupAccountsImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => DashboardSetupRouteRoute,
} as any)

const DashboardHomeStatsRoute = DashboardHomeStatsImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => DashboardHomeRouteRoute,
} as any)

const DashboardHomeOverviewRoute = DashboardHomeOverviewImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DashboardHomeRouteRoute,
} as any)

const DashboardHomeNetWorthRoute = DashboardHomeNetWorthImport.update({
  id: '/net-worth',
  path: '/net-worth',
  getParentRoute: () => DashboardHomeRouteRoute,
} as any)

const DashboardFinancesTransactionsRoute =
  DashboardFinancesTransactionsImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => DashboardFinancesRouteRoute,
  } as any)

const DashboardFinancesBudgetsRoute = DashboardFinancesBudgetsImport.update({
  id: '/budgets',
  path: '/budgets',
  getParentRoute: () => DashboardFinancesRouteRoute,
} as any)

const DashboardBudgetsYearMonthDayRoute =
  DashboardBudgetsYearMonthDayImport.update({
    id: '/budgets/$year/$month/$day',
    path: '/budgets/$year/$month/$day',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/finances': {
      id: '/dashboard/finances'
      path: '/finances'
      fullPath: '/dashboard/finances'
      preLoaderRoute: typeof DashboardFinancesRouteImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/home': {
      id: '/dashboard/home'
      path: '/home'
      fullPath: '/dashboard/home'
      preLoaderRoute: typeof DashboardHomeRouteImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/setup': {
      id: '/dashboard/setup'
      path: '/setup'
      fullPath: '/dashboard/setup'
      preLoaderRoute: typeof DashboardSetupRouteImport
      parentRoute: typeof DashboardRouteImport
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/auth/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/auth/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetImport
      parentRoute: typeof rootRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof rootRoute
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardRouteImport
    }
    '/dashboard/finances/budgets': {
      id: '/dashboard/finances/budgets'
      path: '/budgets'
      fullPath: '/dashboard/finances/budgets'
      preLoaderRoute: typeof DashboardFinancesBudgetsImport
      parentRoute: typeof DashboardFinancesRouteImport
    }
    '/dashboard/finances/transactions': {
      id: '/dashboard/finances/transactions'
      path: '/transactions'
      fullPath: '/dashboard/finances/transactions'
      preLoaderRoute: typeof DashboardFinancesTransactionsImport
      parentRoute: typeof DashboardFinancesRouteImport
    }
    '/dashboard/home/net-worth': {
      id: '/dashboard/home/net-worth'
      path: '/net-worth'
      fullPath: '/dashboard/home/net-worth'
      preLoaderRoute: typeof DashboardHomeNetWorthImport
      parentRoute: typeof DashboardHomeRouteImport
    }
    '/dashboard/home/overview': {
      id: '/dashboard/home/overview'
      path: '/overview'
      fullPath: '/dashboard/home/overview'
      preLoaderRoute: typeof DashboardHomeOverviewImport
      parentRoute: typeof DashboardHomeRouteImport
    }
    '/dashboard/home/stats': {
      id: '/dashboard/home/stats'
      path: '/stats'
      fullPath: '/dashboard/home/stats'
      preLoaderRoute: typeof DashboardHomeStatsImport
      parentRoute: typeof DashboardHomeRouteImport
    }
    '/dashboard/setup/accounts': {
      id: '/dashboard/setup/accounts'
      path: '/accounts'
      fullPath: '/dashboard/setup/accounts'
      preLoaderRoute: typeof DashboardSetupAccountsImport
      parentRoute: typeof DashboardSetupRouteImport
    }
    '/dashboard/setup/categories': {
      id: '/dashboard/setup/categories'
      path: '/categories'
      fullPath: '/dashboard/setup/categories'
      preLoaderRoute: typeof DashboardSetupCategoriesImport
      parentRoute: typeof DashboardSetupRouteImport
    }
    '/dashboard/setup/merchants': {
      id: '/dashboard/setup/merchants'
      path: '/merchants'
      fullPath: '/dashboard/setup/merchants'
      preLoaderRoute: typeof DashboardSetupMerchantsImport
      parentRoute: typeof DashboardSetupRouteImport
    }
    '/dashboard/setup/rules': {
      id: '/dashboard/setup/rules'
      path: '/rules'
      fullPath: '/dashboard/setup/rules'
      preLoaderRoute: typeof DashboardSetupRulesImport
      parentRoute: typeof DashboardSetupRouteImport
    }
    '/dashboard/finances/': {
      id: '/dashboard/finances/'
      path: '/'
      fullPath: '/dashboard/finances/'
      preLoaderRoute: typeof DashboardFinancesIndexImport
      parentRoute: typeof DashboardFinancesRouteImport
    }
    '/dashboard/budgets/$year/$month/$day': {
      id: '/dashboard/budgets/$year/$month/$day'
      path: '/budgets/$year/$month/$day'
      fullPath: '/dashboard/budgets/$year/$month/$day'
      preLoaderRoute: typeof DashboardBudgetsYearMonthDayImport
      parentRoute: typeof DashboardRouteImport
    }
  }
}

// Create and export the route tree

interface DashboardFinancesRouteRouteChildren {
  DashboardFinancesBudgetsRoute: typeof DashboardFinancesBudgetsRoute
  DashboardFinancesTransactionsRoute: typeof DashboardFinancesTransactionsRoute
  DashboardFinancesIndexRoute: typeof DashboardFinancesIndexRoute
}

const DashboardFinancesRouteRouteChildren: DashboardFinancesRouteRouteChildren =
  {
    DashboardFinancesBudgetsRoute: DashboardFinancesBudgetsRoute,
    DashboardFinancesTransactionsRoute: DashboardFinancesTransactionsRoute,
    DashboardFinancesIndexRoute: DashboardFinancesIndexRoute,
  }

const DashboardFinancesRouteRouteWithChildren =
  DashboardFinancesRouteRoute._addFileChildren(
    DashboardFinancesRouteRouteChildren,
  )

interface DashboardHomeRouteRouteChildren {
  DashboardHomeNetWorthRoute: typeof DashboardHomeNetWorthRoute
  DashboardHomeOverviewRoute: typeof DashboardHomeOverviewRoute
  DashboardHomeStatsRoute: typeof DashboardHomeStatsRoute
}

const DashboardHomeRouteRouteChildren: DashboardHomeRouteRouteChildren = {
  DashboardHomeNetWorthRoute: DashboardHomeNetWorthRoute,
  DashboardHomeOverviewRoute: DashboardHomeOverviewRoute,
  DashboardHomeStatsRoute: DashboardHomeStatsRoute,
}

const DashboardHomeRouteRouteWithChildren =
  DashboardHomeRouteRoute._addFileChildren(DashboardHomeRouteRouteChildren)

interface DashboardSetupRouteRouteChildren {
  DashboardSetupAccountsRoute: typeof DashboardSetupAccountsRoute
  DashboardSetupCategoriesRoute: typeof DashboardSetupCategoriesRoute
  DashboardSetupMerchantsRoute: typeof DashboardSetupMerchantsRoute
  DashboardSetupRulesRoute: typeof DashboardSetupRulesRoute
}

const DashboardSetupRouteRouteChildren: DashboardSetupRouteRouteChildren = {
  DashboardSetupAccountsRoute: DashboardSetupAccountsRoute,
  DashboardSetupCategoriesRoute: DashboardSetupCategoriesRoute,
  DashboardSetupMerchantsRoute: DashboardSetupMerchantsRoute,
  DashboardSetupRulesRoute: DashboardSetupRulesRoute,
}

const DashboardSetupRouteRouteWithChildren =
  DashboardSetupRouteRoute._addFileChildren(DashboardSetupRouteRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardFinancesRouteRoute: typeof DashboardFinancesRouteRouteWithChildren
  DashboardHomeRouteRoute: typeof DashboardHomeRouteRouteWithChildren
  DashboardSetupRouteRoute: typeof DashboardSetupRouteRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardBudgetsYearMonthDayRoute: typeof DashboardBudgetsYearMonthDayRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardFinancesRouteRoute: DashboardFinancesRouteRouteWithChildren,
  DashboardHomeRouteRoute: DashboardHomeRouteRouteWithChildren,
  DashboardSetupRouteRoute: DashboardSetupRouteRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardBudgetsYearMonthDayRoute: DashboardBudgetsYearMonthDayRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/finances': typeof DashboardFinancesRouteRouteWithChildren
  '/dashboard/home': typeof DashboardHomeRouteRouteWithChildren
  '/dashboard/setup': typeof DashboardSetupRouteRouteWithChildren
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/finances/budgets': typeof DashboardFinancesBudgetsRoute
  '/dashboard/finances/transactions': typeof DashboardFinancesTransactionsRoute
  '/dashboard/home/net-worth': typeof DashboardHomeNetWorthRoute
  '/dashboard/home/overview': typeof DashboardHomeOverviewRoute
  '/dashboard/home/stats': typeof DashboardHomeStatsRoute
  '/dashboard/setup/accounts': typeof DashboardSetupAccountsRoute
  '/dashboard/setup/categories': typeof DashboardSetupCategoriesRoute
  '/dashboard/setup/merchants': typeof DashboardSetupMerchantsRoute
  '/dashboard/setup/rules': typeof DashboardSetupRulesRoute
  '/dashboard/finances/': typeof DashboardFinancesIndexRoute
  '/dashboard/budgets/$year/$month/$day': typeof DashboardBudgetsYearMonthDayRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/home': typeof DashboardHomeRouteRouteWithChildren
  '/dashboard/setup': typeof DashboardSetupRouteRouteWithChildren
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/finances/budgets': typeof DashboardFinancesBudgetsRoute
  '/dashboard/finances/transactions': typeof DashboardFinancesTransactionsRoute
  '/dashboard/home/net-worth': typeof DashboardHomeNetWorthRoute
  '/dashboard/home/overview': typeof DashboardHomeOverviewRoute
  '/dashboard/home/stats': typeof DashboardHomeStatsRoute
  '/dashboard/setup/accounts': typeof DashboardSetupAccountsRoute
  '/dashboard/setup/categories': typeof DashboardSetupCategoriesRoute
  '/dashboard/setup/merchants': typeof DashboardSetupMerchantsRoute
  '/dashboard/setup/rules': typeof DashboardSetupRulesRoute
  '/dashboard/finances': typeof DashboardFinancesIndexRoute
  '/dashboard/budgets/$year/$month/$day': typeof DashboardBudgetsYearMonthDayRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/finances': typeof DashboardFinancesRouteRouteWithChildren
  '/dashboard/home': typeof DashboardHomeRouteRouteWithChildren
  '/dashboard/setup': typeof DashboardSetupRouteRouteWithChildren
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset': typeof AuthResetRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/finances/budgets': typeof DashboardFinancesBudgetsRoute
  '/dashboard/finances/transactions': typeof DashboardFinancesTransactionsRoute
  '/dashboard/home/net-worth': typeof DashboardHomeNetWorthRoute
  '/dashboard/home/overview': typeof DashboardHomeOverviewRoute
  '/dashboard/home/stats': typeof DashboardHomeStatsRoute
  '/dashboard/setup/accounts': typeof DashboardSetupAccountsRoute
  '/dashboard/setup/categories': typeof DashboardSetupCategoriesRoute
  '/dashboard/setup/merchants': typeof DashboardSetupMerchantsRoute
  '/dashboard/setup/rules': typeof DashboardSetupRulesRoute
  '/dashboard/finances/': typeof DashboardFinancesIndexRoute
  '/dashboard/budgets/$year/$month/$day': typeof DashboardBudgetsYearMonthDayRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/finances'
    | '/dashboard/home'
    | '/dashboard/setup'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/reset'
    | '/auth/signup'
    | '/auth/verify'
    | '/dashboard/'
    | '/dashboard/finances/budgets'
    | '/dashboard/finances/transactions'
    | '/dashboard/home/net-worth'
    | '/dashboard/home/overview'
    | '/dashboard/home/stats'
    | '/dashboard/setup/accounts'
    | '/dashboard/setup/categories'
    | '/dashboard/setup/merchants'
    | '/dashboard/setup/rules'
    | '/dashboard/finances/'
    | '/dashboard/budgets/$year/$month/$day'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/home'
    | '/dashboard/setup'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/reset'
    | '/auth/signup'
    | '/auth/verify'
    | '/dashboard'
    | '/dashboard/finances/budgets'
    | '/dashboard/finances/transactions'
    | '/dashboard/home/net-worth'
    | '/dashboard/home/overview'
    | '/dashboard/home/stats'
    | '/dashboard/setup/accounts'
    | '/dashboard/setup/categories'
    | '/dashboard/setup/merchants'
    | '/dashboard/setup/rules'
    | '/dashboard/finances'
    | '/dashboard/budgets/$year/$month/$day'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/finances'
    | '/dashboard/home'
    | '/dashboard/setup'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/reset'
    | '/auth/signup'
    | '/auth/verify'
    | '/dashboard/'
    | '/dashboard/finances/budgets'
    | '/dashboard/finances/transactions'
    | '/dashboard/home/net-worth'
    | '/dashboard/home/overview'
    | '/dashboard/home/stats'
    | '/dashboard/setup/accounts'
    | '/dashboard/setup/categories'
    | '/dashboard/setup/merchants'
    | '/dashboard/setup/rules'
    | '/dashboard/finances/'
    | '/dashboard/budgets/$year/$month/$day'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AuthForgotRoute: typeof AuthForgotRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetRoute: typeof AuthResetRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthForgotRoute: AuthForgotRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetRoute: AuthResetRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard",
        "/auth/forgot",
        "/auth/login",
        "/auth/reset",
        "/auth/signup",
        "/auth/verify"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard/route.tsx",
      "children": [
        "/dashboard/finances",
        "/dashboard/home",
        "/dashboard/setup",
        "/dashboard/",
        "/dashboard/budgets/$year/$month/$day"
      ]
    },
    "/dashboard/finances": {
      "filePath": "dashboard/finances/route.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/finances/budgets",
        "/dashboard/finances/transactions",
        "/dashboard/finances/"
      ]
    },
    "/dashboard/home": {
      "filePath": "dashboard/home/route.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/home/net-worth",
        "/dashboard/home/overview",
        "/dashboard/home/stats"
      ]
    },
    "/dashboard/setup": {
      "filePath": "dashboard/setup/route.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/setup/accounts",
        "/dashboard/setup/categories",
        "/dashboard/setup/merchants",
        "/dashboard/setup/rules"
      ]
    },
    "/auth/forgot": {
      "filePath": "auth/forgot.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/auth/reset": {
      "filePath": "auth/reset.tsx"
    },
    "/auth/signup": {
      "filePath": "auth/signup.tsx"
    },
    "/auth/verify": {
      "filePath": "auth/verify.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/finances/budgets": {
      "filePath": "dashboard/finances/budgets.tsx",
      "parent": "/dashboard/finances"
    },
    "/dashboard/finances/transactions": {
      "filePath": "dashboard/finances/transactions.tsx",
      "parent": "/dashboard/finances"
    },
    "/dashboard/home/net-worth": {
      "filePath": "dashboard/home/net-worth.tsx",
      "parent": "/dashboard/home"
    },
    "/dashboard/home/overview": {
      "filePath": "dashboard/home/overview.tsx",
      "parent": "/dashboard/home"
    },
    "/dashboard/home/stats": {
      "filePath": "dashboard/home/stats.tsx",
      "parent": "/dashboard/home"
    },
    "/dashboard/setup/accounts": {
      "filePath": "dashboard/setup/accounts.tsx",
      "parent": "/dashboard/setup"
    },
    "/dashboard/setup/categories": {
      "filePath": "dashboard/setup/categories.tsx",
      "parent": "/dashboard/setup"
    },
    "/dashboard/setup/merchants": {
      "filePath": "dashboard/setup/merchants.tsx",
      "parent": "/dashboard/setup"
    },
    "/dashboard/setup/rules": {
      "filePath": "dashboard/setup/rules.tsx",
      "parent": "/dashboard/setup"
    },
    "/dashboard/finances/": {
      "filePath": "dashboard/finances/index.tsx",
      "parent": "/dashboard/finances"
    },
    "/dashboard/budgets/$year/$month/$day": {
      "filePath": "dashboard/budgets/$year/$month/$day.tsx",
      "parent": "/dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
